enableGlobalCache: false

compressionLevel: 'mixed'

packageExtensions:
  "@storybook/nextjs@*":
    dependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-4.4.1.cjs

checksumBehavior: 'update'
