nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.3.1.cjs

npmRegistryServer : "https://registry.yarnpkg.com"

packageExtensions:
  "next@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
      "typescript": "*"
